version: '3.9'

volumes:
   database:

services:
 postgres:
   container_name: postgres13
   image: postgres:13
   environment:
     POSTGRES_USER: myuser
     POSTGRES_PASSWORD: 123456
   ports:
     - "5432:5432"
   volumes:      
     - database:/home/database/
