version: '3.9'

volumes:
   database:

services:
 mysql:
   container_name: mysql8
   image: mysql:8
   environment:
     MYSQL_DATABASE: "test_db"
     MYSQL_USER: myuser
     MYSQL_PASSWORD: 123456
     MYSQL_ROOT_PASSWORD: 123456
   volumes:      
     - database:/home/database/
